# Generated by Django 4.1.4 on 2023-04-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('datetime', models.DateTimeField()),
                ('reserved_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
