# Generated by Django 4.1.8 on 2023-05-02 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_bannerimage_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation_date',
            old_name='is_Full',
            new_name='is_full',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email_address',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
