# Generated by Django 4.1.8 on 2023-04-20 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_bannerimage_reservation_delete_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email_address',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
