# Generated by Django 4.1.4 on 2023-04-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_wines_hide_alter_wines_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wines',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
