# Generated by Django 4.1.4 on 2023-04-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
