# Generated by Django 4.1.8 on 2023-04-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_image2_about_imagebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='About Us Image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imagebanner',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='About Us page banner image'),
        ),
    ]
