# Generated by Django 4.1.4 on 2023-04-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
