# Generated by Django 4.1.8 on 2023-04-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menu_imagebanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='imagebanner',
        ),
        migrations.AddField(
            model_name='category',
            name='imagebanner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
